In [1]:
import pandas as pd
df=pd.read_csv("AptitudeCommunication.csv")
df

       Name  Aptitude  Communication    Class
0    Karuna         2            5.0  Speaker
1    Bhavan         2            6.0  Speaker
2    Gaurav         7            6.0   Leader
3     Parul         7            2.5    Intel
4    Dinesh         8            6.0   Leader
5      Jani         4            7.0  Speaker
6     Bobby         5            3.0    Intel
7   Parimal         3            5.5  Speaker
8    Govind         8            3.0    Intel
9   Sushant         6            5.5   Leader
10    Gauri         6            4.0    Intel
11   Bharat         6            7.0   Leader
12    Rajvi         6            2.0    Intel
13   Pradip         9            7.0   Leader

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           14 non-null     object
 1   Aptitude       14 non-null     int64
 2   Communication  14 non-null     float64
 3   Class          14 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 580.0+ bytes

In [3]:
df.isnull().sum

<bound method DataFrame.sum of      Name  Aptitude  Communication  Class
0   False     False          False  False
1   False     False          False  False
2   False     False          False  False
3   False     False          False  False
4   False     False          False  False
5   False     False          False  False
6   False     False          False  False
7   False     False          False  False
8   False     False          False  False
9   False     False          False  False
10  False     False          False  False
11  False     False          False  False
12  False     False          False  False
13  False     False          False  False>

In [4]:
x=df.iloc[:,1:3]
y=df["Class"]
print(x.shape)
print(y.shape)

(14, 2)
(14,)

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(11, 2)
(3, 2)
(11,)
(3,)

In [6]:
from sklearn.neighbors import KNeighborsClassifier
nn=KNeighborsClassifier(n_neighbors=5)
model=nn.fit(x_train,y_train)
prediction=model.predict(x_test)
print(prediction)

['Intel' 'Speaker' 'Intel']

In [7]:
diff=pd.DataFrame({"Actual":y_test,"Predicted":prediction})
diff

    Actual Predicted
3    Intel     Intel
7  Speaker   Speaker
6    Intel     Intel

In [8]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,prediction)
print(cm)

[[2 0]
 [0 1]]

In [9]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]
print(TN,FP,FN,TP)

2 0 0 1

In [10]:
print("Accuracy Score :",(TP+TN)/(TP+TN+FP+FN))

Accuracy Score : 1.0

In [11]:
print("Error Rate :",(FP+FN)/(TP+TN+FP+FN))

Error Rate : 0.0

In [12]:
print("Sensitivity :",(TP)/(TP+FN))

Sensitivity : 1.0

In [13]:
print("Specificity :",(TN)/(TN+FP))

Specificity : 1.0

In [14]:
print("Precision Score :",(TP)/(TP+FP))

Precision Score : 1.0

In [16]:
import pandas as pd
df=pd.read_csv("DecisionTree_Sports.csv")
df

       Day Weather Temperature Humidity    Wind Play_Sports?
0    Day 1   Sunny         Hot     High    Weak           No
1    Day 2   Sunny         Hot     High  Strong           No
2    Day 3  Cloudy         Hot     High    Weak          Yes
3    Day 4    Rain        Mild     High    Weak          Yes
4    Day 5    Rain        Cool   Normal    Weak          Yes
5    Day 6    Rain        Cool   Normal  Strong           No
6    Day 7  Cloudy        Cool   Normal  Strong          Yes
7    Day 8   Sunny        Mild     High    Weak           No
8    Day 9   Sunny        Cool   Normal    Weak          Yes
9   Day 10    Rain        Mild   Normal    Weak          Yes
10  Day 11   Sunny        Mild   Normal  Strong          Yes
11  Day 12  Cloudy        Mild     High  Strong          Yes
12  Day 13  Cloudy         Hot   Normal    Weak          Yes
13  Day 14    Rain        Mild     High  Strong           No

In [17]:
import pandas as pd
df=pd.read_csv("DecisionTreeDataset -Num.csv")
df

    CGPA  Communication  Apptitude  Programming Skill  Job Offered
0      2              1          1                  1            1
1      1              1          1                  1            1
2      0              0          0                  1            0
3      0              1          0                  0            0
4      2              1          1                  0            1
5      2              1          1                  1            1
6      1              0          0                  0            0
7      1              0          0                  1            0
8      2              0          1                  1            1
9      1              1          1                  1            1
10     0              0          1                  0            0
11     0              0          1                  0            0
12     1              1          1                  0            1
13     0              1          0                  1            0
14     2              0          0                  0            0
15     1              0          1                  1            0
16     2              0          0                  0            0
17     2              1          1                  0            1

In [18]:
x=df.drop("Job Offered",axis=1)
y=df["Job Offered"]
print(x.shape)
print(y.shape)

(18, 4)
(18,)

In [19]:
x.columns

Index(['CGPA', 'Communication', 'Apptitude', 'Programming Skill'], dtype='object')

In [20]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier(criterion="entropy")
model=dtree.fit(x,y)
prediction=model.predict(x)
print(prediction)

[1 1 0 0 1 1 0 0 1 1 0 0 1 0 0 0 0 1]