In [1]:
# sort_values
import pandas as pd

In [2]:
df=pd.DataFrame({"Name":["Alice","Bob","Charlie","David"],
                 "Score":[88,92,86,90]})
df

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     86
3    David     90

In [4]:
sorted_df=df.sort_values(by="Score")
sorted_df

      Name  Score
2  Charlie     86
0    Alice     88
3    David     90
1      Bob     92

In [6]:
sorted_df=df.sort_values(by="Score",ascending=False)
sorted_df

      Name  Score
1      Bob     92
3    David     90
0    Alice     88
2  Charlie     86

In [7]:
df.sort_index(ascending=False)

      Name  Score
3    David     90
2  Charlie     86
1      Bob     92
0    Alice     88

In [8]:
df.set_index("Name",inplace=False)

         Score
Name
Alice       88
Bob         92
Charlie     86
David       90

In [9]:
df.sort_index(ascending=False)

      Name  Score
3    David     90
2  Charlie     86
1      Bob     92
0    Alice     88

In [11]:
# apply()
s=pd.Series([35,67,90,45])
def pass_fail(x):
    return "pass" if x>=50 else "Fail"
result=s.apply(pass_fail)
result

0    Fail
1    pass
2    pass
3    Fail
dtype: object

In [16]:
df=pd.DataFrame({"Physics":[60,70,80],
                 "Chemistry":[65,75,85],
                 "Maths":[70,80,90]})
result=df.apply(sum)
print(result)

Physics      210
Chemistry    225
Maths        240
dtype: int64

In [20]:
result=df.apply(sum,axis=1)
print(result)

0    195
1    225
2    255
dtype: int64

In [21]:
result=df.apply(lambda x:x.mean())
print(result)

Physics      70.0
Chemistry    75.0
Maths        80.0
dtype: float64

In [22]:
df["Total"]=df.apply(lambda x:x.sum(),axis=1)
df

   Physics  Chemistry  Maths  Total
0       60         65     70    195
1       70         75     80    225
2       80         85     90    255

In [24]:
def grade(Total):
    if Total>=250:
        return "A"
    elif Total>=200:
        return "B"
    else:
        return "C"
df["Grade"]=df["Total"].apply(grade)
df

   Physics  Chemistry  Maths  Total Grade
0       60         65     70    195     C
1       70         75     80    225     B
2       80         85     90    255     A

In [28]:
df=pd.DataFrame({"Width":[1,2],"Height":[3,4]})
def get_stats(row): 
    return [row["Width"]*row["Height"],2*(row["Width"]+row["Height"])]
df

   Width  Height
0      1       3
1      2       4

In [29]:
df.apply(get_stats,axis=1,result_type="expand")

   0   1
0  3   8
1  8  12

In [30]:
df.apply(get_stats,axis=1,result_type="reduce")

0     [3, 8]
1    [8, 12]
dtype: object

In [31]:
df.apply(get_stats,axis=1,result_type="broadcast")

   Width  Height
0      3       8
1      8      12

In [33]:
def odd_values(x,y,z):
    return x+y+z
df=pd.DataFrame({"A":[1,2],"B":[10,20]})
df

   A   B
0  1  10
1  2  20

In [34]:
df1=df.apply(odd_values,args=(1,2))
df1

   A   B
0  4  13
1  5  23

In [35]:
def odd_values(x,m):
    return x*m
df=pd.DataFrame({"A":[1,2],"B":[10,20]})
df

   A   B
0  1  10
1  2  20

In [36]:
df1=df.apply(odd_values,m=10)
df1

    A    B
0  10  100
1  20  200

In [37]:
# astype()
df=pd.DataFrame({"A":["1","2","3"],"B":["4","5","6"]})
print(df.dtypes)

A    object
B    object
dtype: object

In [38]:
df["A"]=df["A"].astype(int)
print(df.dtypes)

A     int32
B    object
dtype: object

In [43]:
# replace()
df=pd.DataFrame({"Marks":[80,85,0,90],
                 "Attendance":[75,80,0,85],
                 "Grade":["A","B","F","A"]})
df

   Marks  Attendance Grade
0     80          75     A
1     85          80     B
2      0           0     F
3     90          85     A

In [46]:
result=df.replace(0,60)
result

   Marks  Attendance Grade
0     80          75     A
1     85          80     B
2     60          60     F
3     90          85     A

In [47]:
result=df.replace([80,75],[90,80])
result

   Marks  Attendance Grade
0     90          80     A
1     85          90     B
2      0           0     F
3     90          85     A