In [1]:
import pandas as pd

In [2]:
df1=pd.DataFrame({"A":[1,2],"B":[3,4]})
df2=pd.DataFrame({"A":[5,6],"C":[7,8]})
result=pd.concat([df1,df2],axis=0)
result

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

In [3]:
result=pd.concat([df1,df2],axis=1)
result

   A  B  A  C
0  1  3  5  7
1  2  4  6  8

In [4]:
result=pd.concat([df1,df2],axis=0,join="outer")
result

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

In [5]:
result=pd.concat([df1,df2],axis=0,join="inner")
result

   A
0  1
1  2
0  5
1  6

In [6]:
result=pd.concat([df1,df2],axis=0,join="inner",ignore_index=True)
result

   A
0  1
1  2
2  5
3  6

In [7]:
df1=pd.DataFrame({"E":[1,2],"B":[3,4]})
df2=pd.DataFrame({"C":[5,6],"D":[7,8]})
result=pd.concat([df1,df2],sort=False)
result

     E    B    C    D
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
0  NaN  NaN  5.0  7.0
1  NaN  NaN  6.0  8.0

In [8]:
result=pd.concat([df1,df2],sort=True)
result

     B    C    D    E
0  3.0  NaN  NaN  1.0
1  4.0  NaN  NaN  2.0
0  NaN  5.0  7.0  NaN
1  NaN  6.0  8.0  NaN

In [9]:
# merge()
# merge(left,right,how="inner",on,left_on,right_on,left_index,right_index)
df1=pd.DataFrame({"Employee":["A","B","C"],
                  "Department":["IT","HR","Finance"]})
df2=pd.DataFrame({"Employee":["A","B","D"],
                  "Salary":[50000,40000,30000]})
result=pd.merge(df1,df2,on="Employee")
result

  Employee Department  Salary
0        A         IT   50000
1        B         HR   40000

In [10]:
result=pd.merge(df1,df2,on="Employee",how="outer")
result

  Employee Department   Salary
0        A         IT  50000.0
1        B         HR  40000.0
2        C    Finance      NaN
3        D        NaN  30000.0

In [11]:
result=pd.merge(df1,df2,on="Employee",how="left")
result

  Employee Department   Salary
0        A         IT  50000.0
1        B         HR  40000.0
2        C    Finance      NaN

In [12]:
result=pd.merge(df1,df2,on="Employee",how="right")
result

  Employee Department  Salary
0        A         IT   50000
1        B         HR   40000
2        D        NaN   30000

In [13]:
df1=pd.DataFrame({"Emp_id":[101,102,103],
                  "Name":["Amit","Riya","john"],
                  "Salary":[50000,60000,55000]})
df2=pd.DataFrame({"Emp_id":[101,102,104],
                  "Name":["Amit","Riya","David"],
                  "Salary":[52000,62000,58000]})
result=pd.merge(df1,df2,on="Emp_id")
result

   Emp_id Name_x  Salary_x Name_y  Salary_y
0     101   Amit     50000   Amit     52000
1     102   Riya     60000   Riya     62000

In [14]:
result=pd.merge(df1,df2,on="Emp_id",suffixes=("_left","_right"))
result

   Emp_id Name_left  Salary_left Name_right  Salary_right
0     101      Amit        50000       Amit         52000
1     102      Riya        60000       Riya         62000

In [15]:
df1=pd.DataFrame({"Emp_id":[101,102,103],
                  "Name":["Amit","Riya","john"]})
df2=pd.DataFrame({"Id":[101,102,104],
                  "Salary":[52000,62000,58000]})
result=pd.merge(df1,df2,left_on="Emp_id",right_on="Id")
result

   Emp_id  Name   Id  Salary
0     101  Amit  101   52000
1     102  Riya  102   62000

In [16]:
df1=pd.DataFrame({"Physics":[60,70,80]},
                 index=[101,102,103])
df2=pd.DataFrame({"Name":["Alice","Bob","Charlie"]},
                 index=[101,102,103])
result=pd.merge(df1,df2,left_index=True,right_index=True)
result

     Physics     Name
101       60    Alice
102       70      Bob
103       80  Charlie

In [17]:
df1=pd.DataFrame({"Physics":[60,70,80],
                  "Student_id":[101,102,103]})
df2=pd.DataFrame({"Name":["Alice","Bob","Charlie"]},
                 index=[101,102,103])
result=pd.merge(df1,df2,left_on="Student_id",right_index=True)
result

   Physics  Student_id     Name
0       60         101    Alice
1       70         102      Bob
2       80         103  Charlie

In [18]:
# groupby()
df=pd.DataFrame({"Product Category":["Electronics","Furniture","Electronics","Furniture"],
                 "Sales":[200,150,300,100]})
df

  Product Category  Sales
0      Electronics    200
1        Furniture    150
2      Electronics    300
3        Furniture    100

In [19]:
result=df.groupby("Product Category")
result

In [20]:
result=df.groupby("Product Category")["Sales"].sum()
result

Product Category
Electronics    500
Furniture      250
Name: Sales, dtype: int64

In [21]:
result=df.groupby("Product Category")["Sales"].mean()
result

Product Category
Electronics    250
Furniture      125
Name: Sales, dtype: int64

In [22]:
result=df.groupby("Product Category")["Sales"].median()
result

Product Category
Electronics    250
Furniture      125
Name: Sales, dtype: int64

In [23]:
result=df.groupby("Product Category")["Sales"].describe()
result

                  count   mean        std    min    25%    50%    75%    max
Product Category
Electronics         2.0  250.0  70.710678  200.0  225.0  250.0  275.0  300.0
Furniture           2.0  125.0  35.355339  100.0  112.5  125.0  137.5  150.0

In [24]:
result=df.groupby("Product Category")["Sales"].size()
result

Product Category
Electronics    2
Furniture      2
Name: Sales, dtype: int64

In [25]:
result=df.groupby("Product Category")["Sales"].sample()
result

0    200
1    150
Name: Sales, dtype: int64

In [26]:
result=df.groupby("Product Category")["Sales"].groups
result

{'Electronics': [0, 2], 'Furniture': [1, 3]}

In [27]:
result=df.groupby("Product Category",axis=0,as_index=True,sort=True)["Sales"].count()
result

Product Category
Electronics    2
Furniture      2
Name: Sales, dtype: int64

In [28]:
result=df.groupby("Product Category",axis=0,as_index=False,sort=True)["Sales"].count()
result

  Product Category  Sales
0      Electronics      2
1        Furniture      2

In [29]:
df=pd.DataFrame({"Region":["East","East","West","West","East","West"],
                 "Sales":[100,150,200,120,110,130],
                 "Manager":["A","B","C","D","E","F"]})
df

  Region  Sales Manager
0   East    100       A
1   East    150       B
2   West    200       C
3   West    120       D
4   East    110       E
5   West    130       F

In [30]:
def sales_range(group):
    return group["Sales"].max() - group["Sales"].min()
sales_data=df.groupby("Region").apply(sales_range)
sales_data

Region
East    50
West    80
dtype: int64

In [31]:
df=pd.DataFrame({"Department":["Sales","Sales","HR","HR","IT","IT"],
                 "Salary":[50000,60000,40000,45000,70000,75000],
                 "Bonus":[5000,6000,2000,2500,8000,8500]})
df

  Department  Salary  Bonus
0      Sales   50000   5000
1      Sales   60000   6000
2         HR   40000   2000
3         HR   45000   2500
4         IT   70000   8000
5         IT   75000   8500

In [32]:
result=df.groupby("Department").agg("mean")
result

            Salary  Bonus
Department
HR           42500   2250
IT           72500   8250
Sales        55000   5500

In [33]:
result=df.groupby("Department").agg(["mean","min","max"])
result

           Salary               Bonus
             mean    min    max  mean   min   max
Department
HR          42500  40000  45000  2250  2000  2500
IT          72500  70000  75000  8250  8000  8500
Sales       55000  50000  60000  5500  5000  6000

In [34]:
result=df.groupby("Department").agg({"Salary":["mean","max"],
                                     "Bonus":"sum"})
result

           Salary         Bonus
             mean    max    sum
Department
HR          42500  45000   4500
IT          72500  75000  16500
Sales       55000  60000  11000

In [35]:
result=df.groupby("Department").agg(MeanSalary=("Salary","mean"),
                                     MaxSalary=("Salary","max"),
                                     MinSalary=("Salary","min"))
result

            MeanSalary  MaxSalary  MinSalary
Department
HR               42500      45000      40000
IT               72500      75000      70000
Sales            55000      60000      50000